name: scoped_model
description: A Widget that passes a Reactive Model to all of it's children
version: 0.2.0
author: brian.egan <brian@brianegan.com>
homepage: https://github.com/brianegan/scoped_model

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
